app:
  name: AI Voice Agent
  version: 1.0.0
  environment: development

audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  buffer_size: 4096

speech_recognition:
  default_provider: deepgram
  providers:
    deepgram:
      model: nova-2
      language: en-US
      interim_results: true
      punctuate: true
      diarize: true
      smart_format: true
    talkscriber:
      enabled: false

llm:
  default_provider: openai
  providers:
    openai:
      model: gpt-3.5-turbo
      temperature: 0.7
      max_tokens: 150
    deepseek:
      enabled: false

voice:
  default_provider: elevenlabs
  providers:
    elevenlabs:
      voice_id: default
      stability: 0.5
      similarity_boost: 0.75
    deepgram:
      enabled: false
    cartesia:
      enabled: false

retell:
  enabled: true
  voice_id: default
  language: en-US
  stream_latency: 200
  use_enhanced_model: true
  auto_gain_control: true
  noise_suppression: true

monitoring:
  log_level: INFO
  metrics_enabled: true
  tracing_enabled: true

security:
  token_expiry: 3600
  rate_limit: 100
  ip_whitelist: []
